run:
  timeout: 5m
  issues-exit-code: 1
  tests: true

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - revive
    - gocritic
    - misspell
    - bodyclose
    - noctx
    - goconst
    - gocyclo
    - lll
    - nakedret
    - prealloc
    - unconvert
    - unparam
    - whitespace
    - wsl

linters-settings:
  gocyclo:
    min-complexity: 15
  lll:
    line-length: 140
  nakedret:
    max-func-lines: 30
  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: exported
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unused-parameter
      - name: unreachable-code
      - name: redefines-builtin-id

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
