repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: local
    hooks:
      - id: gofumpt
        name: gofumpt
        entry: go tool gofumpt -w .
        language: system
        types: [go]
        pass_filenames: false
        require_serial: true
      - id: golangci-lint-fix
        name: golangci-lint fix
        entry: go tool golangci-lint run --fix
        language: system
        types: [go]
        pass_filenames: false
        require_serial: true
